### ISSUE TITLE
tags vs aws-resource-tags

### ISSUE THREAD

**Issue by xuan-cao-swi** [solarwindscloud/ec2-runner-action#16]
https://github.com/solarwindscloud/ec2-runner-action/blob/2c9d7bf0b6b27a890199952da491b4d5e7f13546/action.yml#L49-L53

Is this tag same as aws-resource-tags like this [one](https://github.com/machulav/ec2-github-runner/blob/main/action.yml#L57-L63)?

**Comment by raphael-theriault-swi** [comment]
Yes, except the syntax doesn't use JSON
